name: Publish OCI Image using API

on: 
  workflow_dispatch:
  
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  updateSubClaim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create archive
        run: |
          wdir=$(pwd)
          echo ${wdir}
          mkdir -p /tmp
          tar -czvf /tmp/release.tar.gz .             
      - name: verify
        run: |          
          ls -ltr /tmp | grep tar.gz      
      - name: API Publish using GITHUB_TOKEN
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/actions/package?release_id=80312511 \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/octet-stream' \          
          --data-binary "@/tmp/release.tar.gz" \
          --fail
